### ISSUE TITLE
null response in Firefox (but not in Google Chrome)

### ISSUE THREAD

**Issue by kaczmarj** [episphere/vcf#3]
I am using Firefox 123.0.1 and am running into a null response

```js
Uncaught (in promise) TypeError: response.body is null
    fileSize https://episphere.github.io/vcf/vcf.js:960
    initialization https://episphere.github.io/vcf/vcf.js:179
    Vcf https://episphere.github.io/vcf/vcf.js:278
    filterFun https://episphere.github.io/vcf/index.js:593
    handleUrlParams https://episphere.github.io/vcf/index.js:859
    <anonymous> https://episphere.github.io/vcf/:247
```

here is a screen shot in firefox

![image](https://github.com/episphere/vcf/assets/17690870/99e2f6b3-f18a-4790-9402-f6991b3ffe85)

in google chrome, this works.

**Comment by danielruss** [comment]
Thank you for pointing this out.  I see the issue and will put in a PR for the rest of our team to approve.

**Comment by danielruss** [comment]
@kaczmarj Works for me in FF 124.  Thank you again!
